# Generated by Django 5.0.4 on 2024-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='style',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
